name: UI Tests

on: [push]

permissions:
  contents: write

jobs:
  ui-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run UI-tests via docker-compose
        env:
          LOGIN: ${{ secrets.LOGIN }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          docker compose up --exit-code-from regression || true 

      - name: List allure results
        run: ls -la allure-results

      - name: Generate Allure report
        run: |
          docker compose run \
            -v $PWD/allure-results:/app/allure-results \
            -v $PWD/allure-report:/app/allure-report \
            regression /bin/sh -c "allure generate /app/allure-results --clean -o /app/allure-report"

      - name: Verify report
        run: ls -R allure-report

      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.CI_TOKEN }}
          branch: gh-pages
          folder: allure-report
          clean: true